### ISSUE TITLE
如果把使用的模型换成中文模型，可以直接用吗

### ISSUE THREAD

**Issue by jiangzhiyu1016** [weirdseed/Vits-Android-ncnn#3]
如果把使用的模型换成中文模型（转成ncnn格式后），可以直接用吗

**Comment by weirdseed** [comment]
不行，因为目前还不支持中文cleaner，后续可能会支持

**Comment by weirdseed** [comment]
> 如果把使用的模型换成中文模型（转成ncnn格式后），可以直接用吗

目前已支持中文cleaner
